In [11]:
import cv2

#load and preprocess images 

img=cv2.imread("image.png")
height,width,channels= img.shape
print(height,width,channels)

2583 3900 3


In [12]:
import keras
from keras import layers 


#create the sequetial model 
model=keras.Sequential()
model.add(layers.Input(shape=(height,width,channels)))
model.add(layers.Dense(32))
model.add(layers.Dense(16))
model.add(layers.Dense(2))



In [14]:
import numpy as np

preprocessed_img=np.array([img])
result=model(preprocessed_img)
print(result)

tf.Tensor(
[[[[ 138.13931    -86.89013  ]
   [ 128.7275     -80.55988  ]
   [ 135.45024    -85.08149  ]
   ...
   [ 193.93442   -130.15225  ]
   [ 185.86716   -124.72632  ]
   [ 179.39236   -119.946915 ]]

  [[ 148.8957     -94.12473  ]
   [ 136.79478    -85.9858   ]
   [ 139.0063     -87.0963   ]
   ...
   [ 194.18239   -129.8945   ]
   [ 183.42601   -122.6599   ]
   [ 182.08147   -121.75561  ]]

  [[ 139.0063     -87.0963   ]
   [ 140.35085    -88.00062  ]
   [ 140.35085    -88.00062  ]
   ...
   [ 205.77747   -137.38211  ]
   [ 192.33199   -128.33887  ]
   [ 196.36565   -131.05183  ]]

  ...

  [[  18.76709    -12.7542515]
   [  22.800732   -15.467224 ]
   [  22.800732   -15.467224 ]
   ...
   [ 202.56277   -129.64973  ]
   [ 202.24829   -128.83441  ]
   [ 195.52554   -124.31278  ]]

  [[  18.76709    -12.7542515]
   [  25.48983    -17.275873 ]
   [  21.456182   -14.562899 ]
   ...
   [ 202.59105   -129.60292  ]
   [ 201.24652   -128.69858  ]
   [ 201.21822   -128.74542  ]]

  [[  2